services:
  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user_admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - FRONT_ACCESS_URI=http://localhost:4200
      - BACK_NODE_ACCESS_PORT=3000
      - BACK_NODE_ACCESS_URI=http://127.0.0.1:3000
      - MONGODB_URI=mongodb://127.0.0.1:27017
      - MONGODB_AUTH_SOURCE=admin
      - MONGODB_USER=user_admin
      - MONGODB_PASSWORD=password
      - MONGODB_DBNAME=test_db
    stdin_open: true
    tty: true

volumes:
  db:
